# Generated by Django 4.2.3 on 2023-08-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0002_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_key',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ключ для верификации'),
        ),
    ]
