# Generated by Django 4.2.3 on 2023-08-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0004_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_key',
            field=models.IntegerField(blank=True, null=True, verbose_name='ключ для верификации'),
        ),
    ]
