# Generated by Django 4.2.3 on 2023-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0005_alter_customuser_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_key',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='ключ для верификации'),
        ),
    ]
