# Generated by Django 4.2.3 on 2023-08-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0006_alter_customuser_verification_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
