# Generated by Django 4.2.3 on 2023-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='заголовок')),
                ('link', models.CharField(default=models.CharField(max_length=150, verbose_name='заголовок'), max_length=100, verbose_name='ссылка')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('date_when_created', models.DateField(verbose_name='дата создания записи')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована ли статья?')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
        ),
    ]
