# Generated by Django 4.2.3 on 2023-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogarticle_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(max_length=100, verbose_name='ссылка'),
        ),
    ]
