# Generated by Django 4.2.3 on 2023-07-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
