# Generated by Django 4.2.3 on 2023-07-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка'),
        ),
    ]
