# Generated by Django 4.2.3 on 2023-07-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='наименование категории')),
                ('description', models.TextField(verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование товара')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение продукта')),
                ('price', models.IntegerField(verbose_name='цена товара')),
                ('date_when_added', models.DateField(verbose_name='дата добавления товара на сайт')),
                ('date_when_changed', models.DateField(verbose_name='дата изменения информации по товару')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='айди категории')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
