# Generated by Django 4.2.3 on 2023-07-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_unique_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='название компании')),
                ('description', models.TextField(verbose_name='описание')),
                ('address', models.CharField(max_length=150, verbose_name='адрес')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('number', models.CharField(max_length=50, verbose_name='контактный номер')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
