# Generated by Django 4.2.3 on 2023-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_version_product_version_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.FloatField(verbose_name='версия карточки продукта'),
        ),
    ]
