# Generated by Django 4.2.3 on 2023-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_version_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ManyToManyField(to='catalog.product', verbose_name='продукты'),
        ),
    ]
