# Generated by Django 4.2.3 on 2023-08-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_version_product_version_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='product',
            new_name='products',
        ),
    ]
