# Generated by Django 4.2.3 on 2023-08-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_version_version_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='products',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.FloatField(verbose_name='версия карточки продукта'),
        ),
    ]
