# Generated by Django 4.2.3 on 2023-08-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'permissions': [('set_is_active', 'Can cancel product card publication'), ('change_product_description', 'Change product description'), ('change_product_category', 'Change category of product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
